version: '3.8'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: filmograf
    volumes:
      - filmograf_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/filmograf
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  filmograf_data:

networks:
  app-network:
    driver: bridge